import Vue from 'vue'  
import App from './App'  
import VueI18n from 'vue-i18n'  

Vue.use(VueI18n)  
Vue.config.productuinTip = false  

const i18n = new VueI18n({  
  locale: 'zh', 
   platform:false,
  messages: {'zh': {index: {  
add: '发布信息[免费]', 
more:'分类大全',
pay:'充值',
tx:'提现',
mx:'金币清单',
fmore:'个性定制',
addmore: '免费推广您的产品、传播您的声音！',
home:'零久附近通',
mess:'信息',
share:'分享',
browser:'浏览器',
error:'错误',
null:'空',
agree:'同意',
disagree:'不同意',
success:'成功',
select:'选择',
ok:'确定',
copy:'复制',
comment:'评论',
q:'北京',
title:'标题',
content:'内容',
tel:'手机号码',
prc:'价格',
sub:'提交',
tips:'提示',
setting:'设置',
gold:'金币',
credits:'积分',
group:'等级',
sys:'系统',
chat:'聊天',
friend:'朋友',
follow:'关注',
fans:'粉丝',
size:'大小',
save:'保存',
pic:'图片',
login:'登录',
account:'账号',
password:'密码',
verification:'验证码',
obtain:'获取',
generalization:'推广码',
retrieve:'找回密码',
register:'注册',
out:'退出',
clear:'恢复默认设置',
link:'链接',
modetxt:['讨论','宣传','商品','附件','视频'],
top_items:[
{name:'综合',id:'index'},
{name:'收藏',id:'thread'},
{name:'金币',id:'gold'},
],
flist:[
{label:'出行',value:1},
{label:'食物',value:2},
{label:'房屋',value:3},
{label:'购物',value:4},
{label:'兴趣',value:5}
],
favitems:[
'历史',
'收藏',
'精品']
},
drawer:{
nion:'推广返佣',
contact:'客服',
close:'关闭',
mess:'信息',
my:'个人中心',
add:'发布信息',
fav:'我的收藏',
his:'浏览记录',
protocol:'隐私协议',
},
loadingText:{
contentdown: "刷新",
contentrefresh: "加载",
contentnomore:"加载完毕"
}},
'cht': {index: {  
add: '發佈資訊[免費]', 
more:'分類大全',
pay:'充值',
tx:'提現',
mx:'金幣清單',
fmore:'個性定制',
addmore: '免費推廣您的產品、傳播您的聲音！',
home:'零久附近通',
mess:'資訊',
share:'分享',
browser:'瀏覽器',
error:'錯誤',
null:'空',
agree:'同意',
disagree:'不同意',
success:'成功',
select:'選擇',
ok:'確定',
copy:'複製',
comment:'評論',
q:'北京',
title:'標題',
content:'內容',
tel:'手機號碼',
prc:'價格',
sub:'提交',
tips:'提示',
setting:'設定',
gold:'金幣',
credits:'積分',
group:'等級',
sys:'系統',
chat:'聊天',
friend:'朋友',
follow:'關注',
fans:'粉絲',
size:'大小',
save:'保存',
pic:'圖片',
login:'登入',
account:'帳號',
password:'密碼',
verification:'驗證碼',
obtain:'獲取',
generalization:'推廣碼',
retrieve:'找回密碼',
register:'注册',
out:'退出',
clear:'恢復默認設置',
link:'連結',
modetxt:['討論','文宣','商品','附件','視頻'],
top_items:[
{name:'綜合',id:'index'},
{name:'收藏',id:'thread'},
{name:'金幣',id:'gold'},
],
flist:[
{label:'出行',value:1},
{label:'食物',value:2},
{label:'房屋',value:3},
{label:'購物',value:4},
{label:'興趣',value:5}
],
favitems:[
'歷史',
'收藏',
'精品']
},
drawer:{
nion:'推廣返傭',
contact:'客服',
close:'關閉',
mess:'資訊',
my:'個人中心',
add:'發佈資訊',
fav:'我的收藏',
his:'瀏覽記錄',
protocol:'隱私協定',
},
loadingText:{
contentdown: "重繪",
contentrefresh: "加載",
contentnomore:"加載完畢"
}},
'hk': {index: {  
add: '发布信息[免费]', 
more:'分类大全',
pay:'充值',
tx:'提现',
mx:'金币清单',
fmore:'个性定制',
addmore: '免费推广你嘅产品、传播你把声！',
home:'零耐附近通',
mess:'信息',
share:'分享',
browser:'浏览器',
error:'错误',
null:'得闲',
agree:'同意',
disagree:'唔同意',
success:'成功',
select:'拣',
ok:'肯定',
copy:'复制',
comment:'评论',
q:'北京',
title:'标题',
content:'内容',
tel:'手机号码',
prc:'价钱',
sub:'提交',
tips:'显示',
setting:'设置',
gold:'金币',
credits:'积分',
group:'等级',
sys:'系统',
chat:'倾计',
friend:'朋友',
follow:'关注',
fans:'粉丝',
size:'大小',
save:'保存',
pic:'图片',
login:'登录',
account:'账号',
password:'密码',
verification:'验证码',
obtain:'获取',
generalization:'推广码',
retrieve:'搵翻密码',
register:'注册',
out:'退出',
clear:'恢复预设设置',
link:'连结',
modetxt:['讲！','宣传','货','附件','视频'],
top_items:[
{name:'综合',id:'index'},
{name:'收埋。',id:'thread'},
{name:'金币',id:'gold'},
],
flist:[
{label:'出行',value:1},
{label:'嘢食',value:2},
{label:'间屋',value:3},
{label:'购物',value:4},
{label:'兴趣',value:5}
],
favitems:[
'历史。',
'收埋。',
'精品']
},
drawer:{
nion:'推广翻佣',
contact:'客服',
close:'关闭',
mess:'信息',
my:'个人中心。',
add:'发布信息',
fav:'我收藏',
his:'擸一眼纪录',
protocol:'私隐协议',
},
loadingText:{
contentdown: "重绘",
contentrefresh: "载入",
contentnomore:"加载Over"
}},
'en': {index: {  
add: 'Release information[Free Admission]', 
more:'Classification Daquan',
pay:'Recharge',
tx:'Cash withdrawal',
mx:'Gold coin list',
fmore:'Personalized customization',
addmore: 'Free promotion of your products, spread your voice!',
home:'Near zero long',
mess:'information',
share:'share',
browser:'Browser',
error:'error',
null:'empty',
agree:'Agree!',
disagree:'Disagree',
success:'Success',
select:'Choice',
ok:'Determine',
copy:'copy',
comment:'comment',
q:'Beijing',
title:'Title',
content:'content',
tel:'Phone number',
prc:'Price',
sub:'Submission',
tips:'Tips',
setting:'Set up',
gold:'Gold coin',
credits:'integral',
group:'Grade',
sys:'system',
chat:'chat',
friend:'Friend',
follow:'follow',
fans:'Fans',
size:'Size',
save:'Preservation',
pic:'picture',
login:'Sign in',
account:'Account number',
password:'Password',
verification:'Verification Code',
obtain:'Obtain',
generalization:'Generalization code',
retrieve:'Retrieve password',
register:'register',
out:'Sign out',
clear:'Restore default settings',
link:'link',
modetxt:['discuss','Propaganda','commodity','Enclosure','video'],
top_items:[
{name:'comprehensive',id:'index'},
{name:'Collection',id:'thread'},
{name:'Gold coin',id:'gold'},
],
flist:[
{label:'Trip',value:1},
{label:'food',value:2},
{label:'House',value:3},
{label:'Shopping',value:4},
{label:'Interest',value:5}
],
favitems:[
'History',
'Collection',
'Boutique']
},
drawer:{
nion:'Promotion of commission',
contact:'Customer service',
close:'Close',
mess:'information',
my:'Personal Center',
add:'Release information',
fav:'My collection',
his:'Browse record',
protocol:'Privacy protocol',
},
loadingText:{
contentdown: "Refresh",
contentrefresh: "Load",
contentnomore:"Loading completed"
}},
// #ifndef MP-BAIDU
'ja': {index: {  
add: '情報を発表する[無料]', 
more:'分類大全',
pay:'チャージ',
tx:'現金で出す',
mx:'金貨目録',
fmore:'カスタマイズ',
addmore: 'あなたの製品を無料で普及させて、あなたの音を広めます！',
home:'零久近くに通',
mess:'メッセージ',
share:'分かち合う',
browser:'ブラウザ',
error:'エラー',
null:'空',
agree:'首を縦に振る',
disagree:'首を横に振る',
success:'成功',
select:'選択',
ok:'を選択します',
copy:'コピー',
comment:'コメント',
q:'北京',
title:'タイトル',
content:'内容',
tel:'携帯の番号',
prc:'価格',
sub:'送信',
tips:'ヒント',
setting:'設定',
gold:'金貨',
credits:'積分',
group:'レベル',
sys:'システム',
chat:'雑談する',
friend:'友達',
follow:'関心を持つ',
fans:'ファン',
size:'サイズ',
save:'保存',
pic:'画像',
login:'ログイン',
account:'アカウント',
password:'パスワード',
verification:'認証コード',
obtain:'取得',
generalization:'プロモーションコード',
retrieve:'パスワードを取得',
register:'登録する',
out:'終了',
clear:'標準設定を復元',
link:'リンク',
modetxt:['討論する','宣伝する','商品','添付ファイル','動画リスト'],
top_items:[
{name:'総合',id:'index'},
{name:'コレクション',id:'thread'},
{name:'金貨',id:'gold'},
],
flist:[
{label:'旅に出る',value:1},
{label:'食物',value:2},
{label:'家',value:3},
{label:'買い物をする',value:4},
{label:'興味',value:5}
],
favitems:[
'歴史',
'コレクション',
'逸品']
},
drawer:{
nion:'奉公を押し広める',
contact:'顧客サービス',
close:'閉じる',
mess:'メッセージ',
my:'センター',
add:'情報を発表する',
fav:'私のコレクション',
his:'ログをブラウズ',
protocol:'プライバシープロトコル',
},
loadingText:{
contentdown: "更新",
contentrefresh: "読み込み",
contentnomore:"読み込み完了"
}},
'ko': {index: {  
add: '발표 정보[무료]', 
more:'분류 대전',
pay:'충전',
tx:'현금을 제시하다',
mx:'금화 명세서',
fmore:'개성 정제',
addmore: '당신의 제품을 무료로 보급하고 당신의 목소리를 전파합니다!',
home:'영구 부근',
mess:'정보',
share:'나누다',
browser:'브라우저',
error:'잘못',
null:'비다',
agree:'동의',
disagree:'동의하지 않다',
success:'성공',
select:'선택',
ok:'확정',
copy:'복제',
comment:'평론',
q:'북경',
title:'제목',
content:'내용',
tel:'핸드폰 번호',
prc:'가격',
sub:'제출하다',
tips:'힌트',
setting:'설치',
gold:'금화',
credits:'적분',
group:'등급',
sys:'계통',
chat:'한담하다',
friend:'친구',
follow:'관심을 가지다',
fans:'팬',
size:'크기',
save:'보존하다',
pic:'그림',
login:'로그인',
account:'계좌 번호',
password:'암호',
verification:'검증 코드',
obtain:'얻다',
generalization:'보급 코드',
retrieve:'비밀번호 찾기',
register:'등록',
out:'물러나다',
clear:'기본 설정 복구',
link:'링크',
modetxt:['토론하다','선전','상품','첨부 서류','비디오'],
top_items:[
{name:'종합하다',id:'index'},
{name:'수장하다',id:'thread'},
{name:'금화',id:'gold'},
],
flist:[
{label:'가다',value:1},
{label:'음식',value:2},
{label:'가옥',value:3},
{label:'쇼핑',value:4},
{label:'흥미',value:5}
],
favitems:[
'역사',
'수장하다',
'정품']
},
drawer:{
nion:'보급하다.',
contact:'객복',
close:'닫다',
mess:'정보',
my:'개인 센터',
add:'발표 정보',
fav:'나의 소장',
his:'기록을 훑어보다',
protocol:'프라이버시 프로토콜',
},
loadingText:{
contentdown: "새로 고침",
contentrefresh: "가재",
contentnomore:"다운로드 완료"
}},
'es': {index: {  
add: 'Publicar información[Gratis]', 
more:'Clasificación general',
pay:'Recargar',
tx:'Sacar dinero',
mx:'Lista de monedas',
fmore:'Personalizado.',
addmore: 'Se abre en una nueva ventana o pestaña',
home:'Cerca de cero.',
mess:'Información',
share:'Compartir',
browser:'Navegador',
error:'Error',
null:'Vacío',
agree:'Consentimiento',
disagree:'No.',
success:'éxito',
select:'Elección',
ok:'Determinación',
copy:'Copiar',
comment:'Observaciones',
q:'Beijing',
title:'Título',
content:'Contenido',
tel:'Número de teléfono',
prc:'Precio',
sub:'Presentación',
tips:'Pista',
setting:'Configuración',
gold:'Oro',
credits:'Integral',
group:'Grado',
sys:'Sistema',
chat:'Charlar',
friend:'Amigo',
follow:'Preocupación',
fans:'Fanática',
size:'Tamaño',
save:'Guardar',
pic:'Imagen',
login:'Entrada',
account:'Cuenta',
password:'Contraseña',
verification:'Código de verificación',
obtain:'Adquisición',
generalization:'Código de promoción',
retrieve:'Recuperar la contraseña',
register:'Registro',
out:'Denuncia',
clear:'Restaurar configuración predeterminada',
link:'Enlace',
modetxt:['Debate','Difusión','Productos','Anexo','Vídeo'],
top_items:[
{name:'Síntesis',id:'index'},
{name:'Coleccionar',id:'thread'},
{name:'Oro',id:'gold'},
],
flist:[
{label:'Viaje',value:1},
{label:'Comida',value:2},
{label:'Vivienda',value:3},
{label:'Compras',value:4},
{label:'Interés',value:5}
],
favitems:[
'Historia',
'Coleccionar',
'Esperma']
},
drawer:{
nion:'Promoción del retorno',
contact:'Servicio',
close:'Cerrar',
mess:'Información',
my:'Personal Center',
add:'Publicar información',
fav:'Mi colección.',
his:'Historial de navegación',
protocol:'Protocolo de privacidad',
},
loadingText:{
contentdown: "Actualizar",
contentrefresh: "Cargar",
contentnomore:"Carga completa."
}},
'ar': {index: {  
add: 'نشر المعلومات[حرر]', 
more:'تصنيف',
pay:'شحن',
tx:'ذكر',
mx:'قائمة العملات الذهبية',
fmore:'شخصية التخصيص',
addmore: 'تعزيز المنتجات الخاصة بك مجانا ، ونشر الصوت',
home:'بالقرب من الصفر',
mess:'انفورميشن',
share:'شارك',
browser:'براوزر',
error:'خطأ',
null:'فارغ',
agree:'موافقة',
disagree:'اختلف',
success:'نجح',
select:'اختار',
ok:'حدد',
copy:'نسخ',
comment:'تعليق',
q:'بيجينج',
title:'الترويسة',
content:'المحتويات',
tel:'رقم الجوال',
prc:'ثمن',
sub:'قدم',
tips:'تلميح',
setting:'إعداد',
gold:'عملة ذهبية',
credits:'تكاملي',
group:'رتب',
sys:'نظم',
chat:'تشات',
friend:'فريندز',
follow:'اهتمام',
fans:'المشجعين',
size:'مقاس',
save:'حفظ',
pic:'صور ،',
login:'تسجيل الدخول',
account:'رقم الحساب',
password:'باسوورد',
verification:'رمز التحقق',
obtain:'الحصول على',
generalization:'رمز الترويج',
retrieve:'استرجاع كلمة السر',
register:'للتسجيل',
out:'انسحب',
clear:'استعادة الإعدادات الافتراضية',
link:'ربط',
modetxt:['بحث','دعائي','سلعة','المرفقات','ويديو'],
top_items:[
{name:'شامل',id:'index'},
{name:'جمع',id:'thread'},
{name:'عملة ذهبية',id:'gold'},
],
flist:[
{label:'رحلة',value:1},
{label:'مأكولات',value:2},
{label:'إسكان',value:3},
{label:'تسوق',value:4},
{label:'اهتمام',value:5}
],
favitems:[
'هیستوری',
'جمع',
'بوتيك']
},
drawer:{
nion:'تشجيع العائدين',
contact:'خدمة العملاء',
close:'مغلق',
mess:'انفورميشن',
my:'مركز شخصي',
add:'نشر المعلومات',
fav:'بلدي المفضل',
his:'تصفح السجلات',
protocol:'بروتوكول الخصوصية',
},
loadingText:{
contentdown: "منعش",
contentrefresh: "اللودينج",
contentnomore:"نهاية التحميل"
}},
'ru': {index: {  
add: 'опубликовать информацию[бесплатный]', 
more:'полная классификация',
pay:'наполнение',
tx:'представлять',
mx:'Список золотых монет',
fmore:'индивидуальный заказ',
addmore: 'Бесплатное распространение вашей продукции и ваш голос!',
home:'близкий к нулю',
mess:'сведения',
share:'делить',
browser:'браузер',
error:'ошибка',
null:'пустота',
agree:'согласие',
disagree:'несогласие',
success:'успех',
select:'выбор',
ok:'определение',
copy:'копировать',
comment:'Замечания',
q:'пекин',
title:'заголовок',
content:'Содержание',
tel:'номер телефона',
prc:'цена',
sub:'представление',
tips:'подсказка',
setting:'Настройки',
gold:'золотая монета',
credits:'интеграл',
group:'сорт',
sys:'система',
chat:'разговор',
friend:'друг',
follow:'озабоченность',
fans:'вермишель',
size:'размер',
save:'Сохранить',
pic:'рисунок',
login:'вход',
account:'номер счета',
password:'пароль',
verification:'код проверки',
obtain:'добывать',
generalization:'широтно - импульсный распространения',
retrieve:'получить пароль',
register:'регистрация',
out:'выход',
clear:'восстановить настройки по умолчанию',
link:'ссылка',
modetxt:['Обсуждение','Распространение информации','товар','Приложение','видео'],
top_items:[
{name:'синтез',id:'index'},
{name:'коллекция',id:'thread'},
{name:'золотая монета',id:'gold'},
],
flist:[
{label:'выезд',value:1},
{label:'пища',value:2},
{label:'дом',value:3},
{label:'покупка',value:4},
{label:'интерес',value:5}
],
favitems:[
'история',
'коллекция',
'изысканный']
},
drawer:{
nion:'продвигать обратно на работу',
contact:'принимать гостей',
close:'закрыть',
mess:'сведения',
my:'персональный центр',
add:'опубликовать информацию',
fav:'моя коллекция',
his:'просмотр записи',
protocol:'частная жизнь',
},
loadingText:{
contentdown: "Обновить",
contentrefresh: "загрузка",
contentnomore:"Загрузка завершена"
}},
'fr': {index: {  
add: 'Diffusion d &#39;informations[Gratuit]', 
more:'Classification',
pay:'Recharger',
tx:'Présenter',
mx:'Liste des pièces d &#39;or',
fmore:'Personnalisation',
addmore: 'Promotion gratuite de vos produits, la diffusion de votre voix!',
home:'Zero - ku',
mess:'Information',
share:'Partager',
browser:'Browser',
error:'Erreur',
null:'Vide',
agree:'D&#39;accord.',
disagree:'Désaccord',
success:'Succès',
select:'Choix',
ok:'Oui.',
copy:'Copier',
comment:'Observations',
q:'Beijing.',
title:'Titre',
content:'Contenu',
tel:'Numéro de téléphone',
prc:'Prix',
sub:'Soumettre',
tips:'Avertissement',
setting:'Set',
gold:'Pièce d &#39;or',
credits:'Integration',
group:'Grade',
sys:'Système',
chat:'Bavarder',
friend:'Ami',
follow:'Préoccupation',
fans:'Fan',
size:'Taille',
save:'Enregistrer',
pic:'Photo.',
login:'Connecter',
account:'Numéro de compte',
password:'Mot de passe',
verification:'Code d &#39;authentification',
obtain:'Acquisition',
generalization:'Code de diffusion',
retrieve:'Retrouver le mot de passe',
register:'Enregistrement',
out:'Retrait',
clear:'Restaurer les paramètres par défaut',
link:'Lien',
modetxt:['Débat','Diffusion','Produits de base','Annexe','Vidéo'],
top_items:[
{name:'Synthèse',id:'index'},
{name:'Collection',id:'thread'},
{name:'Pièce d &#39;or',id:'gold'},
],
flist:[
{label:'Voyage',value:1},
{label:'Nourriture',value:2},
{label:'Maison',value:3},
{label:'Shopping',value:4},
{label:'Intérêt',value:5}
],
favitems:[
'Histoire',
'Collection',
'Elite']
},
drawer:{
nion:'Promotion du retour',
contact:'Smoking',
close:'Fermer',
mess:'Information',
my:'Centre personnel',
add:'Diffusion d &#39;informations',
fav:'Ma collection',
his:'Browser record',
protocol:'Privacy Agreement',
},
loadingText:{
contentdown: "Rafraîchir",
contentrefresh: "Chargement",
contentnomore:"Chargement terminé."
}},
'vi': {index: {  
add: 'Thông tin[Miễn phí nhập]', 
more:'Hạng Nhất',
pay:'Nạp',
tx:'Rút tiền mặt',
mx:'Danh sách vàng',
fmore:'Tự chọn',
addmore: 'Sự quảng bá miễn phí cho sản phẩm của bạn, hãy truyền giọng!',
home:'Gần không dài',
mess:'Thông',
share:'chia',
browser:'Name=KDBBrowserComment',
error:'lỗi',
null:'rỗng',
agree:'Chiến!',
disagree:'Không',
success:'Xong',
select:'Chọn',
ok:'Chọn',
copy:'Rõ',
comment:'Ghi',
q:'Bắc',
title:'Tựa',
content:'nội dung',
tel:'Số điện thoại',
prc:'Nguồn:',
sub:'Gởi',
tips:'Mẹo',
setting:'Chuẩn bị',
gold:'Tiền vàng',
credits:'Name',
group:'Hạng',
sys:'Comment',
chat:'chat',
friend:'Bạn',
follow:'theo',
fans:'Name',
size:'Cỡ',
save:'Bảo:',
pic:'ảnh',
login:'Ký vô.',
account:'Số tài khoản',
password:'Mật khẩu',
verification:'Mật khẩu',
obtain:'Đầu',
generalization:'Mã gia vị',
retrieve:'Thu hồi mật khẩu',
register:'ghi',
out:'Ký tên vô.',
clear:'Khôi phục thiết lập mặc định',
link:'Comment',
modetxt:['thảo','Name','hàng','Name','video'],
top_items:[
{name:'toàn',id:'index'},
{name:'Bộ',id:'thread'},
{name:'Tiền vàng',id:'gold'},
],
flist:[
{label:'Trip',value:1},
{label:'thức ăn',value:2},
{label:'Nhà',value:3},
{label:'Mua',value:4},
{label:'Tiền',value:5}
],
favitems:[
'Lịch',
'Bộ',
'Boutique']
},
drawer:{
nion:'Truyền dịch hoa hồng',
contact:'Dịch vụ khách hàng',
close:'Đóng',
mess:'Thông',
my:'Trung tâm cá nhân',
add:'Thông tin',
fav:'Bộ sưu tập',
his:'Ghi chép duyệt',
protocol:'Giao thức riêng',
},
loadingText:{
contentdown: "Cập nhật",
contentrefresh: "Tải",
contentnomore:"Nạp xong"
}},
'th': {index: {  
add: 'เผยแพร่ข้อมูล[แจกฟรี]', 
more:'หมวดหมู่ทั่วไป',
pay:'เติม',
tx:'ถอนเงิน',
mx:'รายการทอง',
fmore:'การปรับแต่งบุคลิกภาพ',
addmore: 'ฟรีเพื่อส่งเสริมผลิตภัณฑ์ของคุณและเผยแพร่เสียงของคุณ',
home:'ใกล้ศูนย์ยาว',
mess:'กราบบังคมทูลพระกรุณา',
share:'แบ่งปัน',
browser:'เบราว์เซอร์',
error:'ข้อผิดพลาด',
null:'โล่งว่าง',
agree:'เห็นด้วย',
disagree:'ไม่เห็นด้วย',
success:'ประสบความสำเร็จ',
select:'คัดเลือก',
ok:'ยืนยัน',
copy:'ทำสำเนา',
comment:'แสดงความคิดเห็น',
q:'ปักกิ่ง•',
title:'หัวเรื่อง',
content:'เนื้อหา',
tel:'หมายเลขโทรศัพท์มือถือ',
prc:'ราคา',
sub:'ทูลเกล้าฯถวาย',
tips:'ทูลเกล้าฯถวาย',
setting:'ตั้งค่า',
gold:'เหรียญทอง',
credits:'จุดสำคัญ',
group:'ชนชั้น',
sys:'ระบบ',
chat:'พูดคุย',
friend:'เพื่อน',
follow:'เอาใจใส่',
fans:'แฟน',
size:'มัวซัว',
save:'เก็บรักษา',
pic:'รูปภาพ',
login:'ล็อกอิน',
account:'อธิบายแจกแจง',
password:'รหัสผ่าน',
verification:'รหัสการตรวจสอบ',
obtain:'ได้รับ',
generalization:'รหัสโปรโมชั่น',
retrieve:'กู้คืนรหัสผ่าน',
register:'ลงทะเบียน',
out:'ถอนตัว',
clear:'เรียกคืนการตั้งค่าเริ่มต้น',
link:'เชื่อมโยง',
modetxt:['การอภิปราย','ธารกำนัล','สินค้า','แนบท้าย','วีดีโอ'],
top_items:[
{name:'สังเคราะห์',id:'index'},
{name:'คำอธิษฐานสั้น',id:'thread'},
{name:'เหรียญทอง',id:'gold'},
],
flist:[
{label:'การล่วงเกิน',value:1},
{label:'อาหาร',value:2},
{label:'บ้านเรือน',value:3},
{label:'ซื้อของ',value:4},
{label:'ข้าพระบาท',value:5}
],
favitems:[
'ประวัติศาสตร์',
'คำอธิษฐานสั้น',
'ความดีงาม']
},
drawer:{
nion:'ส่งเสริมให้คนรับใช้',
contact:'เว็บบอร์ด',
close:'ปิดกล้อง',
mess:'กราบบังคมทูลพระกรุณา',
my:'ศูนย์บุคคล',
add:'เผยแพร่ข้อมูล',
fav:'ของสะสมของฉัน',
his:'เรียกดูประวัติ',
protocol:'ข้อตกลงความเป็นส่วนตัว',
},
loadingText:{
contentdown: "ทำให้สดชื่น",
contentrefresh: "น้ำหนักบรรทุก",
contentnomore:"โหลดเสร็จ"
}},
'pt': {index: {  
add: 'Informação de lançamento[Admissão gratuita]', 
more:'Classificação Daquan',
pay:'Recarregamento',
tx:'Retirada de numerário',
mx:'Lista de moedas douradas',
fmore:'Personalização personalizada',
addmore: 'Promoção gratuita de seus produtos, espalhe SUA voz!',
home:'Quase zero de comprimento',
mess:'Informação',
share:'Partilha',
browser:'Navegador',
error:'Erro',
null:'Vazio',
agree:'Concordo!',
disagree:'Discorda',
success:'Sucesso',
select:'Escolha',
ok:'Determinar',
copy:'Cópia',
comment:'Comentário',
q:'Pequim.',
title:'Denominação',
content:'Conteúdo',
tel:'Número de telefone',
prc:'Preço',
sub:'Apresentação',
tips:'Dicas',
setting:'Preparar para',
gold:'Moedas de Ouro',
credits:'Integral',
group:'Grau',
sys:'Sistema',
chat:'Conversa',
friend:'Amigo.',
follow:'Seguir',
fans:'Fãs',
size:'Tamanho',
save:'Conservação',
pic:'Imagem',
login:'Assine aqui.',
account:'Número Da conta',
password:'Senha',
verification:'Código de verificação',
obtain:'Obter',
generalization:'Código de generalização',
retrieve:'Recuperar senha',
register:'Registar',
out:'Assine aqui.',
clear:'Restaurar configurações predefinidas',
link:'Ligação',
modetxt:['Discutir','Propaganda.','Mercadorias','Anexo','Vídeo'],
top_items:[
{name:'Abrangente',id:'index'},
{name:'Colecção',id:'thread'},
{name:'Moedas de Ouro',id:'gold'},
],
flist:[
{label:'Viagem',value:1},
{label:'Alimentos',value:2},
{label:'Casa',value:3},
{label:'Compras',value:4},
{label:'Interesse',value:5}
],
favitems:[
'História',
'Colecção',
'Boutique.']
},
drawer:{
nion:'Promoção Da comissão',
contact:'Serviço Ao cliente',
close:'Fechar',
mess:'Informação',
my:'Centro Pessoal',
add:'Informação de lançamento',
fav:'Minha coleção',
his:'Registo de Navegação',
protocol:'Protocolo de privacidade',
},
loadingText:{
contentdown: "Actualizar",
contentrefresh: "Carregar",
contentnomore:"Carregamento concluído"
}},
'de': {index: {  
add: 'Informationen zur Veröffentlichung[Freier Eintritt]', 
more:'Einstufung Daquan',
pay:'Aufladung',
tx:'Auszahlung der Mittel',
mx:'Gold Münzliste',
fmore:'Personalisierte Anpassung',
addmore: 'Kostenlose Förderung Ihrer Produkte, verbreiten Sie Ihre Stimme!',
home:'Nahe Null lang',
mess:'Informationen',
share:'Aktie',
browser:'Browser',
error:'Fehler',
null:'leer',
agree:'Einverstanden!',
disagree:'Uneinigkeit',
success:'Erfolg',
select:'Auswahl',
ok:'Bestimmen',
copy:'Kopie',
comment:'Kommentar',
q:'Peking',
title:'Titel',
content:'Inhalt',
tel:'Telefon Nummer',
prc:'Preis',
sub:'Einreichung',
tips:'Tipps',
setting:'Set up',
gold:'Gold Münze',
credits:'Integral',
group:'Grad',
sys:'System',
chat:'chat',
friend:'Freund',
follow:'folgen',
fans:'Ventilatoren',
size:'Größe',
save:'Erhaltung',
pic:'Bild',
login:'Melden Sie sich',
account:'Nummer des Kontos',
password:'Passwort',
verification:'Code der Überprüfung',
obtain:'Erwerb',
generalization:'Code der Generierung',
retrieve:'Passwort abrufen',
register:'Register',
out:'Melden Sie sich',
clear:'Standardeinstellungen wiederherstellen',
link:'Link',
modetxt:['diskutieren','Propaganda','Ware','Gehäuse','Video'],
top_items:[
{name:'umfassend',id:'index'},
{name:'Erhebung',id:'thread'},
{name:'Gold Münze',id:'gold'},
],
flist:[
{label:'Reise',value:1},
{label:'Lebensmittel',value:2},
{label:'Haus',value:3},
{label:'Einkaufen',value:4},
{label:'Zinsen',value:5}
],
favitems:[
'Geschichte',
'Erhebung',
'Boutique']
},
drawer:{
nion:'Förderung der Provision',
contact:'Service Service',
close:'Schließen',
mess:'Informationen',
my:'Persönliches Zentrum',
add:'Informationen zur Veröffentlichung',
fav:'Meine Sammlung',
his:'Datensatz durchsuchen',
protocol:'Privacy Protokoll',
},
loadingText:{
contentdown: "Aktualisieren",
contentrefresh: "Laden",
contentnomore:"Laden abgeschlossen"
}},
// #endif
}  
})  

Vue.prototype._i18n  = i18n  
App.mpType = 'app'  

const app = new Vue({  
  i18n,  
  ...App  
})  
app.$mount()